### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by aXises** [monkey-team-3801/on-board#17]
**Specifications**
Homepage Epic:

- [x] Page design and view implementation. #18 
- [ ] Calendar / Timetable, Students can schedule their work and classes. All time table entries are managed and provided by the calendar. It should also display upcoming reminders. #20 
- [x] Announcements system which allows coordinators to announce important messages. #21 
- [x] Current active classes / streams. #22 
- [x] Ability to see available tutors for consulting. #23
