### ISSUE TITLE
Student side classroom

### ISSUE THREAD

**Issue by aXises** [monkey-team-3801/on-board#27]
**Specifications**
Student Side Classroom Epic:

- [ ] Live systems (slide show, video etc) #34 
- [ ] Settings configuration #35 
- [ ] Session time remaining #20 
- [ ] Session recording #37 
- [x] List of participants #38 
- [x] Messaging system #30 
- [x] Avatar system #39 
- [ ] Alternative interface #40 
- [x] Material downloading #41
