### ISSUE TITLE
Coordinator side classroom

### ISSUE THREAD

**Issue by aXises** [monkey-team-3801/on-board#28]
**Specifications**
Coordinator side classroom epic:

- [x] Ability to post questions and gather responses. #33 
- [x] Ability to upload and distribute materials #42 . 
- [ ] Ability to stream live data (e.g screen) #34 .
- [x] Ability to place students into separate sessions #43.
