### ISSUE TITLE
 Messaging system

### ISSUE THREAD

**Issue by aXises** [monkey-team-3801/on-board#30]
**Specifications**
Many areas of the proposal require a chat messaging system whether if its a group chat or private chat.

We will need to associate each session type with a list of messages, and form `chatSessions` between users.
- [x] User to user chat #31 
- [x] Global session chat associated with each session (room/streams) #32 #33 

Currently, setting simple text-messaging will be enough.

Some more complex features will be required such as
- [x] Special message types (forms which gather responses) #33 
- [x] Important message types
